# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [51]:
A = np.arange(1, 16).reshape(3,5)
# I am printing the A matrix for my own understanding
print('A:', '\n', A) # Using '\n' for creating a new line after A

A: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [3]:
# Printing the dimension (number of axis)
print('Dimension:', A.ndim)

Dimension: 2


In [4]:
# Shape
print('Shape:', A.shape)

Shape: (3, 5)


In [5]:
# Size
print('Size:', A.size)

Size: 15


In [6]:
# Type
print('Type:', A.dtype)

Type: int32


In [7]:
# (Just printing it for my understanding) printing a specific row
print('Second row:', A[1])

Second row: [ 6  7  8  9 10]


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [12]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print('B:', '\n', B)
print()  # to give space between B and C

print('C:', '\n', C)

B: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

C: 
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [103]:
# Elementwise subtraction
print('B-C:', '\n',B-C)

B-C: 
 [[-2 -2]
 [ 1  1]]


In [106]:
# Elemetwise multiplication (elementwise multiplication and matrcies multiplication is not the same thing. When each element of the two Matrices is multiplied, that is elementwise multiplication.
print('B*C:', '\n', B*C)

B*C: 
 [[8 3]
 [0 6]]


In [110]:
# Matrcies multiplication (this multiplication is the multiplication that we learned from the book Matrix Algebra for Engineers)
print('B@C:', '\n', B@C)

B@C: 
 [[8 8]
 [4 9]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [112]:
B = np.arange(1, 10).reshape(3, 3)

print('B:', '\n',B)
print()

print('Dimension:', B.ndim) # Printing dimension for my own understanding

B: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimension: 2


In [118]:
# Exponentiate each number elementwise
E=np.exp(B)
print(E)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [116]:
# Calculate the minimum value in the whole matrix.
print('Minimum value of B:', np.min(B))

Minimum value of B: 1


In [117]:
# (I am doing it out of my own interest) Calculate the maximum value in the whole matrix. 
print('Maximum value of B:', np.max(B))

Maximum value of B: 9


In [20]:
# Calculcate the minimum value in each row considering that axis=0 for row number 1 and continue afterwards
print('Minimum value in each row:', np.min(B, axis=0))

Minimum value in each row: [1 2 3]


In [21]:
# Just checking myself to see the maximum values in each row
print('Maximum value in each row:', np.max(B, axis=0))

Maximum value in each row: [7 8 9]


In [22]:
# Calculcate the minimum value in each column considering that axis=1 for coulmn number 1 and continue afterwards
print('Minimum value in each column:', np.min(B, axis=1))

Minimum value in each column: [1 4 7]


In [23]:
# Just checking myself to see the maximum values in each column
print('Maximum value in each column:', np.max(B, axis=1))

Maximum value in each column: [3 6 9]


In [119]:
# Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
# It will show us the postion of row and column in the matrix
print('Index value for the minimum value in B:', np.argmin(B))

Index value for the minimum value in B: 0


In [25]:
# Find the index value for the minimum value in each row (hint: use np.argmin).
print('Index value for the minimum value in each row:', np.argmin(B, axis = 1))

Index value for the minimum value in each row: [0 0 0]


In [26]:
# Want to check myself for the minimum value in each column
print('Index value for the minimum value in each column:',np.argmin(B, axis = 1))

Index value for the minimum value in each column: [0 0 0]


In [120]:
# Calculate the sum for all elements
print('Sum the all elements in B:', np.sum(B))

Sum the all elements in B: 45


In [28]:
# Calculate the mean for each column
print('Mean for each column:', np.mean(B, axis = 1))

Mean for each column: [2. 5. 8.]


In [29]:
# Checking myself the mean for each row
print('Mean for each row:', np.mean(B, axis = 0))

Mean for each row: [4. 5. 6.]


In [30]:
# Calculate the median for each column
print('Median for each column:', np.median(B, axis = 1))

Median for each column: [2. 5. 8.]


In [31]:
# Checking myself the median for each row
print('Median for each row:', np.median(B, axis = 0))

Median for each row: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

**Answer:**

In [121]:
A = np.arange(1, 16).reshape(3,5)

print('A:', '\n', A)

A: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [123]:
# To find a specific row in a matrix

print('First row of A:', A[0])
print()

print('Second row of A:', A[1])
print()

print('Third row of A:', A[2])

First row of A: [1 2 3 4 5]

Second row of A: [ 6  7  8  9 10]

Third row of A: [11 12 13 14 15]


Answer: 

When slicing with fewer indices than there are axes, the missing indices are assumed full slices or complete slices, which means including all the elements along those dimensions. 

In [124]:
# In the above matrix, A[:2] slices the array along the first axis (towards the rows) with a start index of 0 and an end index of 2.
print('First two rows of A:', '\n', A[:2])

First two rows of A: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [31]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
# Finding iterating through rows considering that row is the first axis and the result will show the elements wihtout commas
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [40]:
for i in A.ravel(): # using ravel method to iterate the array elementwise
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [41]:
for i in A.flatten(): #using flatten method to iterate the array elementwise
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

Answer: 

If the b matrices has 3 rows which means it has 3 axes 0,1 and 2 respectively considering that it has suitable numbers of columns.

In [50]:
a = np.arange(30) # it means we want to create 1 dimensional matrix from 0-29
b = a.reshape((2, 3, -1)) # it means we want to create 3 dimensional matrices from 0-29

print('a:', '\n', a)
print() # making spaces in the result between two matrices

print('B:','\n',b)  

a: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

B: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [49]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])

# We can check the shapes of the matrices m1 and m2 first
print('Shape of m1:', m1.shape)
print()

print('Shape of m2:', m2.shape)
print()

print('m1+m2:', '\n', m1+m2) #This is not possilbe in mathematical rules in Linear Algebra but poosible in Numpy by broadcasting

Shape of m1: (2, 2)

Shape of m2: (2,)

m1+m2: 
 [[2 3]
 [4 5]]


In [125]:
v1 = np.array([1, 2, 3])

print('v1+1:', v1 + 1)

v1+1: [2 3 4]


In [126]:
A = np.arange(1, 5).reshape(2,2)
print('A:', '\n', A)
print()

b = np.array([2, 2])
print('b:', '\n', b)
print()

print('A+b:', '\n', A+b) # b matrix has 1 row which is added to the each rows of A matrix (2 rows) respectively

A: 
 [[1 2]
 [3 4]]

b: 
 [2 2]

A+b: 
 [[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [127]:
A = np.array([[2, 1, -1], [1, -1, 1]])

B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])

D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print('A:', '\n', A)
print()

print('B:', '\n', B)
print()

print('C:', '\n', C)
print()

print('D:', '\n', D)
print()

print('E:', '\n', E)

A: 
 [[ 2  1 -1]
 [ 1 -1  1]]

B: 
 [[ 4 -2  1]
 [ 2 -4 -2]]

C: 
 [[1 2]
 [2 1]]

D: 
 [[3 4]
 [4 3]]

E: 
 [[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [60]:
# Writing the function "add_mult_matrices":

def add_mult_matrices(A, B, add_or_multiply):
    
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise Exception('Please provide two matrices.')
    
    if add_or_multiply == 'add':
        if not A.shape == B.shape:
            raise ValueError('Same shape required for matrix addition.')
        else: 
            return A + B
        
    elif add_or_multiply == 'multiply':
        if not A.shape[1] == B.shape[0]:
            raise ValueError('Columns and rows must be the shame length in matrix multiplication.')
        else:
            return A @ B
        
    else:
        raise Exception('the add_or_multiply argument must be "add" or "multiply". ')

In [61]:
# Find B-2A which meets the condtions of above function
print('B-2A:', '\n', add_mult_matrices(B, -2*A, 'add'))

B-2A: 
 [[ 0 -4  3]
 [ 0 -2 -4]]


In [63]:
# Find 3C-E  which is not valid due to the conditions of above function
print('3C-E:', '\n', add_mult_matrices(3*C, -E, 'add'))

ValueError: Same shape required for matrix addition.

In [64]:
# Find AC which is not valid due to the conditions of above function
print('AC:', '\n', add_mult_matrices(A, C, 'multiply'))

ValueError: Columns and rows must be the shame length in matrix multiplication.

In [65]:
# Find CD which meets the condtions of above function
print('CD:', '\n', add_mult_matrices(C, D, 'multiply'))

CD: 
 [[11 10]
 [10 11]]


In [66]:
# Find CB which meets the condtions of above function
print('CB:', '\n', add_mult_matrices(C, B, 'multiply'))

CB: 
 [[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [128]:
# Writing A, B and C matrices in np.array format
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print('A:', '\n', A)
print()

print('B:', '\n', B)
print()

print('C:', '\n', C)

AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')
print()

print('AB:', '\n', AB)
print()

print('AC:', '\n', AC)
print()


print((AB == AC).all())  # AB=AC but B is not equal to C.
print()

print((B == C).all()) 

A: 
 [[1 2]
 [2 4]]

B: 
 [[2 1]
 [1 3]]

C: 
 [[4 3]
 [0 2]]

AB: 
 [[ 4  7]
 [ 8 14]]

AC: 
 [[ 4  7]
 [ 8 14]]

True

False


In [129]:
# To find AB:
print('AB:', '\n', add_mult_matrices(A, B, 'multiply'))
print()

# To find AC:
print('AC:', '\n', add_mult_matrices(A, C, 'multiply'))

AB: 
 [[ 4  7]
 [ 8 14]]

AC: 
 [[ 4  7]
 [ 8 14]]


**Chap2. Question 3**

In [70]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print('A:', '\n', (A))
print()

print('B:', '\n', B)

A: 
 [[1 1 1]
 [1 2 3]
 [1 3 4]]

B: 
 [[2 1]
 [1 3]]


In [71]:
# To find AD:
print('AD:', '\n', add_mult_matrices(A, D, 'multiply'))
print()

# To find DA:
print('DA: ', '\n', add_mult_matrices(D, A, 'multiply'))

AD: 
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

DA:  
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [72]:
M1 = np.array([[1, -1], [-1, 1]])
M2 = np.array([[-1, 1], [1, -1]])

print('M1:', '\n', M1)
print()

print('M2:', '\n', M2)

M1: 
 [[ 1 -1]
 [-1  1]]

M2: 
 [[-1  1]
 [ 1 -1]]


In [53]:
print('M1M2: ', '\n', add_mult_matrices(M1, M2, 'multiply'))

M1M2:  
 [[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [136]:
M1 = np.array([[5, 6], [4, 5]])
print('M1:', '\n', M1)
print()

# To find inverse matrix of M1
M1_inv = np.linalg.inv(M1) # uses of np.linalg.inv to find out inverse matrix
print('Inverse of M1:', '\n', M1_inv)
print()

# Checking if M1 @ M1_inv is the identity matrix. Remember: that due to round-off error in the computer, we need to use np.allclose
print('M1*Inverse of M1:', '\n', M1 @ M1_inv)
print()

print(np.allclose(M1 @ M1_inv, np.eye(2)))

M1: 
 [[5 6]
 [4 5]]

Inverse of M1: 
 [[ 5. -6.]
 [-4.  5.]]

M1*Inverse of M1: 
 [[ 1.00000000e+00  0.00000000e+00]
 [-3.55271368e-15  1.00000000e+00]]

True


In [138]:
M2 = np.array([[6, 4], [3, 3]])
print('M2:', '\n', M2)
print()

# To find inverse matrix of M2
M2_inv = np.linalg.inv(M2)
print('Inverse of M2:', '\n', M2_inv)
print()

# Checking if M2 @ M2_inv is the identity matrix. Remember: that due to round-off error in the computer, we need to use np.allclose
print('M2*Inverse of M2:', '\n', M2 @ M2_inv)
print()

print(np.allclose(M2 @ M2_inv, np.eye(2)))

M2: 
 [[6 4]
 [3 3]]

Inverse of M2: 
 [[ 0.5        -0.66666667]
 [-0.5         1.        ]]

M2*Inverse of M2: 
 [[1. 0.]
 [0. 1.]]

True


**Quiz p.19, Question 3**

In [139]:
M = np.array([[2, 2], [1, 2]])
print('M:', '\n', M)
print()

M_inv = np.linalg.inv(M)
print('Inverse of M:', '\n', M_inv)
print()

print('M*Inverse of M:', '\n', M @ M_inv)
print()

# Checking if M1 @ M1_inv is the identity matrix
print(np.allclose(M @ M_inv, np.eye(2)))

M: 
 [[2 2]
 [1 2]]

Inverse of M: 
 [[ 1.  -1. ]
 [-0.5  1. ]]

M*Inverse of M: 
 [[1. 0.]
 [0. 1.]]

True


**Chap10. Question 1 a)**

In [143]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])

print('A:', '\n', A)
print()

print('b:', '\n', b)

A: 
 [[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

b: 
 [-7  5  2]


In [144]:
# To find the solution to the system of equations:
x = np.linalg.solve(A, b)
print('Solution of A and b:', x)

Solution of A and b: [ 3.  4. -6.]


In [146]:
# Double checking if Ax = b
print('A*x:', A @ x)

A*x: [-7.  5.  2.]


**Chap10. Question 1 b)**

In [84]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])

print('A:', '\n', A)
print()

print('b:', '\n', b)

A: 
 [[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]

b: 
 [ 1 -1  1]


In [147]:
# To find the solution to the system of equations:
x = np.linalg.solve(A, b)
print('Solution of A and b:', x)

Solution of A and b: [ 3.  4. -6.]


In [148]:
# Double checking if Ax = b
print('A*x:', A @ x)

A*x: [-7.  5.  2.]


**Chap 12. Question 1**

In [150]:
M = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
print('M:', '\n', M)

M: 
 [[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]


In [151]:
# To find inverse matrix of M
M_inv = np.linalg.inv(M)
print('Inverse of M:', '\n', M_inv)
print()

# Checking if M1 @ M1_inv is the identity matrix
print(np.allclose(M @ M_inv, np.eye(3)))

Inverse of M: 
 [[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]

True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

Answer: 

At first, we will find out "View" in return, afterwards "Copy" in return. If it is a "View" then it will return the same array, on the other hand, it is a "Copy" then it will return "None". 

If we change the last element in v2 then the last element in v1 will also be changed hence v2 is a "View" which means they share the same data buffer.

We can see these in below three cells separately.

In [93]:
v1 = np.arange(4)
v2 = v1[-2:]

print('v1:', v1)
print()

print('v2:', v2)

v1: [0 1 2 3]

v2: [2 3]


In [152]:
# Explanation: The base attribute of a "Copy" returns "None", on the other hand, "View" returns the original array
print('Return of Copy:', v1.base)
print()

print('Return of View:', v2.base)

Return of Copy: None

Return of View: [  0   1   2 123]


In [153]:
# The last element in v2 then the last element in v1 will also be changed hence v2 is a "View" which means they share the same data buffer
v2[-1] = 123
print('Changed last element in v1:', v1)
print()

print('Changed last element in v2:', v2)

Changed last element in v1: [1 2 3]

Changed last element in v2: [  2 123]
